apiVersion: v2
description: Wrapper chart for the Nuxeo application on Google Cloud Marketplace
name: nuxeo-mp
version: 2.11.3
appVersion: 2025.17
dependencies:
  - name: nuxeo
    version: 3.1.24
    repository: https://packages.nuxeo.com/repository/helm-releases-public/
