nuxeo:
  image:
    repository: us-docker.pkg.dev/hyl-is-marketplace/nuxeo/nuxeo
    tag: 2.0.0
  serviceAccount:
    create: false
  startupProbe:
    # It seems that in the test GKE clusters, the Nuxeo container takes a longer time to startup.
    # Let's wait for 2 minutes before running the readiness and liveness probes.
    initialDelaySeconds: 120
  ingress:
    # true if `INGRESS_AVAILABLE` is true, aka the cluster has an Ingress controller
    enabled: false
    className: null
    hostname: null
    path: null
    tls:
      secretName: nuxeo-tls
  # Billing agent sidecar
  extraContainers:
    - name: ubbagent
      image: "{{ .Values.ubbagent.image.repository }}:{{ .Values.ubbagent.image.tag }}"
      env:
        - name: AGENT_CONFIG_FILE
          value: /etc/ubbagent/config.yaml
        - name: AGENT_LOCAL_PORT
          value: "4567"
        - name: AGENT_REPORT_DIR
          value: /var/lib/ubbagent/reports
        - name: AGENT_STATE_DIR
          value: /var/lib/ubbagent
        - name: AGENT_ENCODED_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.ubbagent.reportingSecret }}"
              key: reporting-key
        - name: AGENT_CONSUMER_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.ubbagent.reportingSecret }}"
              key: consumer-id
      volumeMounts:
        - name: ubbagent-config
          mountPath: /etc/ubbagent
        - name: ubbagent-state
          mountPath: /var/lib/ubbagent
  extraVolumes:
    - name: ubbagent-config
      configMap:
        name: ubbagent-config
    - name: ubbagent-state
      emptyDir: {}
  ubbagent:
    image:
      repository: gcr.io/cloud-marketplace-tools/metering/ubbagent
      tag: latest
    reportingSecret: null
tls:
  base64EncodedPrivateKey: null
  base64EncodedCertificate: null
