{{- if and .Values.nuxeo.ingress.enabled (and .Values.tls.base64EncodedPrivateKey .Values.tls.base64EncodedCertificate) }}
apiVersion: v1
kind: Secret
metadata:
  name: nuxeo-tls
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
data:
  tls.key: |
    {{- .Values.tls.base64EncodedPrivateKey | nindent 4 }}
  tls.crt: |
    {{- .Values.tls.base64EncodedCertificate | nindent 4 }}
type: kubernetes.io/tls
{{- end }}
